apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: back
  name: back
spec:
  selector:
    matchLabels:
      io.kompose.service: back
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: back
    spec:
      containers:
        image: aosmon17/quotes-back:v1
        env: 
          name: SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: backsecret
              key: DATABASE_URI
        name: api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}