apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: data-script
  name: data-script
spec:
  selector:
    matchLabels:
      io.kompose.service: data-script
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: data-script
    spec:
      containers:
      - name: data-script
        image: aosmon17/quotes-script:v1
        env:
        - name: MYSQL_DB_HOST
          valueFrom:
            secretKeyRef:
              name: scriptsecret
              key: host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: scriptsecret
              key: user    
        - name: MYSQL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scriptsecret
              key: password                        
        resources: {}
      initContainers:
      - name: init-script
        image: busybox:1.28
        env:
        - name: MYSQL_DB_HOST
          valueFrom:
            secretKeyRef:
              name: scriptsecret
              key: host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: scriptsecret
              key: user    
        - name: MYSQL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scriptsecret
              key: password 
        command: ['sh', '-c', "until mysql -h ${MYSQL_DB_HOST} -u ${MYSQL_USER} -p${MYSQL_USER_PASSWORD} -e 'show databases;'; do echo 'waiting for mydb'; sleep 2; done"]
      restartPolicy: Always
status: {}